# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e27b3a90c55ee9f42c65d1bddecba29"
application_url = "https://cant-elder-ent-veterinary.trycloudflare.com"
embedded = true
name = "code-whize"
handle = "code-whize"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cant-elder-ent-veterinary.trycloudflare.com/auth/callback",
  "https://cant-elder-ent-veterinary.trycloudflare.com/auth/shopify/callback",
  "https://cant-elder-ent-veterinary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "parth-v2.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
